.gitignore
build.gradle
src/main/java/com/myplace/myplace/common/ErrorResponse.java
src/main/java/com/myplace/myplace/common/ErrorType.java
src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
src/main/java/com/myplace/myplace/jwt/JwtAuthFilter.java
src/main/java/com/myplace/myplace/jwt/JwtUtil.java
src/main/java/com/myplace/myplace/member/controller/MemberController.java
src/main/java/com/myplace/myplace/member/entity/Member.java
src/main/java/com/myplace/myplace/member/repository/MemberRepository.java
src/main/java/com/myplace/myplace/member/service/MemberService.java
src/main/java/com/myplace/myplace/security/CustomAuthenticationEntryPoint.java
src/main/java/com/myplace/myplace/security/UserDetailsImpl.java
src/main/java/com/myplace/myplace/security/UserDetailsServiceImpl.java

- 시큐리티 설정 적용
- 사용자 인증객체를 만들기 위해  Member Entity, Repository 구현
- 시큐리티 필터 내 예외처리를 위한 ErrorResponse, ErrorType 작성
- 시큐리티 필터 내 예외처리 구현
closes #3

Feat: #3 Spring Security 적용

---

src/main/java/com/myplace/myplace/serverTest/TestController.java
src/main/java/com/myplace/myplace/serverTest/TestResponseDto.java
src/main/java/com/myplace/myplace/serverTest/TestService.java

Get "/test" 요청을 보내면 { "msg" : "hello" } 를 리턴한다.
closes #18

Feat: #18 프론트와 서버 통신 테스트를 위한 API 코드 작성

---

src/main/java/com/myplace/myplace/config/WebSecurityConfig.java

test API 주소를 permitAll 하도록 수정
closes #3

Fix: #3 permitAll 경로 수정

---

src/main/java/com/myplace/myplace/serverTest/TestController.java

TestService에 final 붙여서 DI 가능하도록 수정
closes #18

Fix: #18 TestController 코드 수정

---

build.gradle
src/main/java/com/myplace/myplace/common/ErrorType.java
src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
src/main/java/com/myplace/myplace/member/controller/MemberController.java
src/main/java/com/myplace/myplace/member/dto/SignupRequestDto.java
src/main/java/com/myplace/myplace/member/entity/Member.java
src/main/java/com/myplace/myplace/member/repository/MemberRepository.java
src/main/java/com/myplace/myplace/member/service/MemberService.java
src/main/resources/application.yml

회원가입 기능 API 구현 완료
- 에러처리는 공통 예외처리 구현하면 처리할 예정

Feat: #4 signup 회원가입 기능 API 구현 완료

---

src/main/java/com/myplace/myplace/common/ErrorType.java
src/main/java/com/myplace/myplace/member/controller/MemberController.java
src/main/java/com/myplace/myplace/member/dto/LoginRequestDto.java
src/main/java/com/myplace/myplace/member/service/MemberService.java

로그인 정보가 일치하지 않는 경우(아이디가 없거나, 비밀번호가 일치하지 않을 때) 에러메시지 ErrorType에 추가
closes #5

Feat: #5 로그인 API 기능 구현 완료

---

src/main/java/com/myplace/myplace/restaurant/controller/RestaurantController.java
src/main/java/com/myplace/myplace/restaurant/entity/Restaurant.java
src/main/java/com/myplace/myplace/restaurant/repository/RestaurantRepository.java
src/main/java/com/myplace/myplace/restaurant/service/RestaurantService.java

- 음식점(Restaurant) 엔티티 생성
- @PostConstruct 사용하여 애플리케이션 실행 시 음식점 샘플 데이터 저장
closes #28

Feat: #28 음식점 Entity 생성 및 정보 저장

---

src/main/java/com/myplace/myplace/MyplaceApplication.java
src/main/java/com/myplace/myplace/review/entity/Review.java

1. NoArgsConstructor 추가
2. @EnableJpaAuditing 추가
close #30

Chore : #30 리뷰 Entity 생성

---

src/main/java/com/myplace/myplace/visit/entity/Visit.java
src/main/java/com/myplace/myplace/visit/repository/VisitRepository.java
src/main/java/com/myplace/myplace/visit/service/VisitService.java

- 방문(Visit) 엔티티 생성
- @PostConstruct 사용하여 애플리케이션 실행 시 방문 샘플 데이터 저장

Feat: #29 방문 Entity 생성 및 샘플 데이터 저장

---

src/main/java/com/myplace/myplace/common/ErrorType.java
src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
src/main/java/com/myplace/myplace/review/entity/Keyword.java
src/main/java/com/myplace/myplace/review/entity/KeywordType.java
src/main/java/com/myplace/myplace/review/entity/Review.java
src/main/java/com/myplace/myplace/review/entity/ReviewKeyword.java
src/main/java/com/myplace/myplace/review/repository/KeywordRepository.java
src/main/java/com/myplace/myplace/review/repository/ReviewKeywordRepository.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

- Keyword 관련 엔티티 생성 및 연관관계 매핑
- 리뷰 작성 API 기능 구현
- 리뷰 작성 관련 에러 메시지 추가
* 리뷰 이미지 등록 관련 추가 작업 필요

Feat: #12 리뷰 작성 API 기능 구현

---

src/main/java/com/myplace/myplace/FileUploadController.java
src/main/java/com/myplace/myplace/S3Config.java

1. FileUploadController
2. S3config

Feat : S3 관련 파일 업로드

---

src/main/java/com/myplace/myplace/common/MessageType.java
src/main/java/com/myplace/myplace/visit/controller/VisitController.java
src/main/java/com/myplace/myplace/visit/dto/VisitResponseDto.java
src/main/java/com/myplace/myplace/visit/repository/VisitRepository.java
src/main/java/com/myplace/myplace/visit/service/VisitService.java

Feat : #9 방문 조회 구현

---

src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java

#9 Feat : 방문 조회 Repository 추가
close #9

#9 Feat : 방문 조회 Repository 추가

---

src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
src/main/java/com/myplace/myplace/review/entity/Review.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

- s3Uploader 사용하여 리뷰 사진 등록 구현
- 키워드 저장시 for문 한번만 사용하도록 리팩토링 포함하여 수정
- MultipartFile 을 받도록 dto 수정 -> setter 필요
- 컨트롤러에서 @ModelAttribute 사용하여 requestDto에서 MultipartFile을 받을 수 있도록 구현
closes #12

Feat: #12 리뷰 사진 등록 기능 구현

---

src/main/java/com/myplace/myplace/member/entity/Member.java

Feat: #6 사용자 기본 이미지 주소 설정

---

src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/ReviewResponseDto.java
src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

#8 Feat : [피드, 리뷰] 상세 조회 API 구현 
close #8

#8 Feat : [피드, 리뷰] 상세 조회 API 구현 

---

src/main/java/com/myplace/myplace/review/service/ReviewService.java

- 리뷰 작성 부분 member imgUrl 수정 불필요하므로 삭제
- 리뷰 수정 merge 하면서 review 찾는 부분이 삭제되어서 다시 추가
close #12 
close #13

Fix: #12 #13 리뷰 작성 및 수정 fix

---

src/main/java/com/myplace/myplace/s3/service/S3Uploader.java

UUID를 활용하여 16진수 랜덤값 + 확장자로 파일명을 변경하여 S3에 저장한다.

Feat: #6 S3 이미지 업로드 시 파일명 난수화

---

src/main/java/com/myplace/myplace/like/controller/LikeController.java
src/main/java/com/myplace/myplace/review/controller/ReviewController.java

* 좋아요 API 요청 URL 변경
* merge 하면서 삭제된 함수 닫기 기호 추가
closes #15

Fix: 좋아요 API 요청 URL 변경 및 함수 닫기 기호 추가

---

src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
src/main/java/com/myplace/myplace/like/controller/LikeController.java
src/main/java/com/myplace/myplace/like/entity/Like.java
src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java
src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
src/main/java/com/myplace/myplace/review/dto/ReviewResponseDto.java
src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java
src/main/java/com/myplace/myplace/s3/service/S3Uploader.java
src/main/java/com/myplace/myplace/visit/controller/VisitController.java

Feat : #8 상세 조회 API Dto 구현
close #8

Feat : #8 상세 조회 API Dto 구현

---

src/main/java/com/myplace/myplace/common/ErrorType.java
src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/FeedPageResponseDto.java
src/main/java/com/myplace/myplace/review/dto/FeedReviewResponseDto.java
src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

* 피드 전체 리뷰 조회 API 구현
* 피드 전체 조회 exception 처리
* reviewRepository 쿼리 메서드 수정

Feat: #7 피드 리뷰 전체 조회 API 기능 구현

---

src/main/java/com/myplace/myplace/visit/service/VisitService.java

Feat : #9 상세 조회 API Dto 구현
close #9

Chore : #9 service 변경

---

src/main/java/com/myplace/myplace/common/ErrorResponse.java
src/main/java/com/myplace/myplace/common/GlobalExceptionHandler.java

- @Valid 예외 발생한 경우 예외처리 구현
- 예외처리 시, log 남기도록 구현

Feat: #16 예외처리 추가

---

src/main/java/com/myplace/myplace/serverTest/TestService.java
src/main/java/com/myplace/myplace/visit/service/VisitService.java

Test: 샘플 데이터 저장

---

src/main/java/com/myplace/myplace/common/SuccessResponseDto.java
src/main/java/com/myplace/myplace/review/entity/Review.java

* 공통 응답 필드 값 null인 경우 숨김 처리
* 리뷰 contents 컬럼 타입 text로 변경

Refactor: #22 공통 응답 필드 값 null인 경우 처리 및 리뷰 컬럼 타입 변경

---

src/main/java/com/myplace/myplace/member/controller/MemberController.java
src/main/java/com/myplace/myplace/member/dto/LoginResponseDto.java
src/main/java/com/myplace/myplace/member/service/MemberService.java

Feat: #5 로그인 response 구현

---

src/main/java/com/myplace/myplace/review/entity/Review.java
src/main/java/com/myplace/myplace/review/entity/ReviewKeyword.java

- @OneToMany mappedBy 설정
- column name 오타 수정

Fix: Entity DDL 관련 수정

---

src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

리뷰 삭제시 저장된 좋아요 함께 삭제
closes #14

Fix: #14 리뷰 삭제시 저장된 좋아요 함께 삭제

---

src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
src/main/java/com/myplace/myplace/visit/service/VisitService.java

user가 한 음식점에 리뷰를 여러개 쓸 수 있으므로 `findByMemberAndRestaurant`를 List로 받는다.
closes #9

Fix: #9 방문 조회 시 리뷰 작성 여부 확인 수정

---

src/main/java/com/myplace/myplace/like/dto/LikeResponseDto.java
src/main/java/com/myplace/myplace/like/service/LikeService.java

1. LikeResponseDto에서 isPushed 추가.
2. LikeService에서 삭제/추가에서 boolean 조건 추가.

Feat : #15 리뷰 좋아요 반환 값 추가

---

src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/FeedReviewResponseDto.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

- 유저가 해당 리뷰에 좋아요를 누른 경우, isPushed = true
- 유저가 해당 리뷰에 좋아요를 안 누른 경우(미로그인 포함), isPushed = false
closes #7

Feat: #7 전체 피드 조회 시, 유저가 리뷰에 좋아요 눌렀는지 여부 확인

---

src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

Feat : #8 좋아요 관련 기능 추가
close #8

Feat : #8 좋아요 관련 기능 추가

---

src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java
src/main/java/com/myplace/myplace/serverTest/TestController.java
src/main/java/com/myplace/myplace/serverTest/TestService.java

Chore : #8 데이터 추가

---

src/main/java/com/myplace/myplace/MyplaceApplication.java

1. MyplaceApplication 파일 추가 ( https로 리다이렉션 작업 )

Feat : #31 https 서버 배포

---

src/main/java/com/myplace/myplace/visit/controller/VisitController.java
src/main/java/com/myplace/myplace/visit/service/VisitService.java

- Optional<List<Review>>로 받으면 비어있는 리스트로 존재하므로 isPresent()가 항상 true이므로, 사이즈 비교로 조건문 수정
- 미로그인 경우(토큰 X, member X) 빈 배열 리턴
closes #9

Fix: #9 작성한 리뷰가 있는 경우 조건문 수정 및 미로그인 처리

---

src/main/java/com/myplace/myplace/review/controller/ReviewController.java
src/main/java/com/myplace/myplace/review/service/ReviewService.java

Chore : #10 [리뷰]리뷰 조회 수정
close #10

Chore : #10 [리뷰]리뷰 조회 수정

---

src/main/java/com/myplace/myplace/member/controller/MemberController.java
src/main/java/com/myplace/myplace/member/dto/ProfileResponseDto.java
src/main/java/com/myplace/myplace/member/service/MemberService.java

프로필 이미지 등록 후 수정된 img url 리턴
closes #6

Feat: #6 프로필 이미지 등록 후 수정된 img url 리턴

---

src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java

Chore : #8 상세 조회 코드 추가
close #8

Chore : #8 상세 조회 코드 추가

---

src/main/java/com/myplace/myplace/review/controller/ReviewController.java

Chore : #13 리뷰 수정 코드 수정
close #13

Chore : #13 리뷰 수정 코드 수정

---

src/main/java/com/myplace/myplace/member/controller/MemberController.java
src/main/java/com/myplace/myplace/member/dto/MemberInfoResponseDto.java
src/main/java/com/myplace/myplace/member/service/MemberService.java

닉네임과 프로필 이미지를 리턴한다.
closes #81

Feat: #81 로그인 사용자 정보 조회 API 구현

---

src/main/java/com/myplace/myplace/member/dto/MemberInfoResponseDto.java
src/main/java/com/myplace/myplace/member/service/MemberService.java
src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java

로그인 사용자 정보 조회 시 작성 리뷰 개수 리턴
closes #81

Feat: #81 로그인 사용자 정보 조회 시 작성 리뷰 개수 리턴
